#ifndef mulle__iovec_h__
#define mulle__iovec_h__

#include "include.h"

#include <stdint.h>

#include <stddef.h>
#include <sys/types.h>


struct mulle_iovec
{
   void   *iov_base;
   size_t iov_len;
};


#if defined( __unix__) || defined( __APPLE__) || defined( __linux__)
# include <sys/uio.h>
# include <stddef.h>

# define MULLE_IOVEC_NATIVE   1

// Compile-time assertions to ensure mulle_iovec is compatible with system iovec
_Static_assert( sizeof( struct mulle_iovec) == sizeof( struct iovec),
                "struct mulle_iovec size must match struct iovec");
_Static_assert( offsetof( struct mulle_iovec, iov_base) == offsetof( struct iovec, iov_base),
                "iov_base offset must match between mulle_iovec and iovec");
_Static_assert( offsetof( struct mulle_iovec, iov_len) == offsetof( struct iovec, iov_len),
                "iov_len offset must match between mulle_iovec and iovec");
_Static_assert( sizeof( ((struct mulle_iovec*)0)->iov_base) == sizeof( ((struct iovec*)0)->iov_base),
                "iov_base field size must match between mulle_iovec and iovec");
_Static_assert( sizeof( ((struct mulle_iovec*)0)->iov_len) == sizeof( ((struct iovec*)0)->iov_len),
                "iov_len field size must match between mulle_iovec and iovec");

static inline ssize_t
   mulle_readv( int fd, struct mulle_iovec *iov, int iovcnt)
{
   return( readv( fd, (struct iovec *) iov, iovcnt));
}


static inline ssize_t
   mulle_writev( int fd, struct mulle_iovec *iov, int iovcnt)
{
   return( writev( fd, (struct iovec *) iov, iovcnt));
}

#elif defined( _WIN32)
# include "mulle-iovec-windows.h"

# define MULLE_IOVEC_NATIVE   1

static inline ssize_t
   mulle_readv( int fd, struct mulle_iovec *iov, int iovcnt)
{
   return( mulle_readv_windows( fd, iov, iovcnt));
}


static inline ssize_t
   mulle_writev( int fd, struct mulle_iovec *iov, int iovcnt)
{
   return( mulle_writev_windows( fd, iov, iovcnt));
}

#else
# define MULLE_IOVEC_EMULATED   1

MULLE__IOVEC_GLOBAL
ssize_t
   mulle_readv( int fd, struct mulle_iovec *iov, int iovcnt);

MULLE__IOVEC_GLOBAL
ssize_t
   mulle_writev( int fd, struct mulle_iovec *iov, int iovcnt);

#endif


/*
 *  (c) <|YEAR|> nat <|ORGANIZATION|>
 *
 *  version:  major, minor, patch
 */
#define MULLE__IOVEC_VERSION  ((0UL << 20) | (7 << 8) | 56)


static inline unsigned int   mulle_iovec_get_version_major( void)
{
   return( MULLE__IOVEC_VERSION >> 20);
}


static inline unsigned int   mulle_iovec_get_version_minor( void)
{
   return( (MULLE__IOVEC_VERSION >> 8) & 0xFFF);
}


static inline unsigned int   mulle_iovec_get_version_patch( void)
{
   return( MULLE__IOVEC_VERSION & 0xFF);
}


MULLE__IOVEC_GLOBAL
uint32_t   mulle_iovec_get_version( void);


/*
 * The following files are auto-generated.
 * The _mulle-iovec-provide header is generated by
 * mulle-match-to-c during a reflect.
 */
#include "_mulle-iovec-provide.h"

/*
 * The versioncheck header can be generated with
 * mulle-project-dependency-versions, but it is optional.
 */
#ifdef __has_include
# if __has_include( "_mulle-iovec-versioncheck.h")
#  include "_mulle-iovec-versioncheck.h"
# endif
#endif

#endif
